version: "3"

services:

  odom_test:
    image: ros2_x86_no_gpu:latest
    command: bash -c "source /usr/share/gazebo/setup.sh && source /ws_test/install/setup.bash && launch_test /ws_test/src/integration_gazebo_test/test/launch_odom_test.py"
    network_mode: host
    privileged: true
    environment:
      DISPLAY:
      QT_X11_NO_MITSHM: 1
      TURTLEBOT3_MODEL: waffle
      GAZEBO_MODEL_PATH: $GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models
    container_name: odom_test
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"

